# Generated by Django 5.2.15 on 2026-06-05 01:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('telepon', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(choices=[('MASYARAKAT', 'Masyarakat'), ('ADMIN', 'Admin')], default='MASYARAKAT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Pengaduan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=500)),
                ('deskripsi', models.TextField()),
                ('kategori', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=500)),
                ('foto', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Belum diterima', max_length=100)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='laporan', to='api.user')),
            ],
            options={
                'db_table': 'Pengaduan',
            },
        ),
    ]
